### ISSUE TITLE
I can't connect to the ftp server (ESP32-WROOM-32).

### ISSUE THREAD

**Issue by DavideLentini** [SpotlightKid/micropython-ftplib#15]
Hi , I don't know if I am doing something wrong .
I have an esp-32 :
https://www.az-delivery.de/it/products/esp32-developmentboard
With micropython installed , and I am using Thonny .
I loaded on the esp32 , the` ftplib.py `file .
And then in the` boot.py` file I added the line : 

`from ftplib import FTP`

In main.py , after I connect to the wifi network , I try to access an ftp server local on the ip 192.168.1.1 

the part of code dedicated to ftp in main.py is :

```
ftp= FTP('192.168.1.1',21,'user','password')
print('done')

```
When I try to run the code an error message comes up : 

`Could not connect to('192.168.1.1',21)
`
I confirm that the server is working ( i login in it with my computer) , and that the esp32 is able to ping the ip 192.168.1.1

EDIT:
Maybe i was wrong , i realized thay maybe i was using the wrong library , i have to use the library inside the esp folder right?

**Comment by SpotlightKid** [comment]
Hard to diagnose from here. Try:

```py
from ftplib import FTP

class DebuggingFTP(FTP):
    debugging = True

ftp = DebuggingFTP('192.168.1.1',21,'user','password')
```

and that should print the actual exceptions raised when connecting fails.

Edit https://github.com/SpotlightKid/micropython-ftplib/blob/master/ftplib.py#L242 if you want a traceback.

**Comment by SpotlightKid** [comment]
> i have to use the library inside the esp folder right?

Correct.

**Comment by DavideLentini** [comment]
Thanks ! I'll try tonight again , with the library in the esp folder :)

**Comment by DavideLentini** [comment]
It worked , it was my error . Sorry for the issue
