### ISSUE TITLE
Problem with ftp.example.py test 

### ISSUE THREAD

**Issue by Ricmelis80** [SpotlightKid/micropython-ftplib#16]
Hy!

I'll try to test " ftplib.py" in my Rasp Pico W using Thonny IDE.

When I run "ftp_example.py" as is, the follow error msn appears 

```
Testing
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "ftplib.py", line 160, in __init__
  File "ftplib.py", line 217, in connect
  File "ftplib.py", line 180, in _create_connection
  File "ftplib.py", line 71, in _resolve_addr
OSError: -6
```

**Comment by SpotlightKid** [comment]
Sorry, I need more information than that to get an idea of what went wrong.

You might want to put `print(repr(host), repr(addr))` before line 71 of `esp/ftplib.py` to debug this.  

The Pico W is not tested or supported, see also #13.

**Comment by Ricmelis80** [comment]
Hy!
I put the additional line as suggested but problem still persist 

```
def _resolve_addr(addr):
    if isinstance(addr, (bytes, bytearray)):
        return addr

    if not addr[0]:
        host = "127.0.0.1" if len(addr) == 2 else "::1"
    else:
        host = addr[0]
        print(repr(host), repr(addr))
    return _socket.getaddrinfo(host, addr[1])
```

I suppose this is also related with the use of pico W version as you punctualized

**Comment by SpotlightKid** [comment]
Please put the print call directly before the return statement, with the same indentation as that.

Then run the code again and report what it prints out here.

**Comment by Ricmelis80** [comment]
Hy again,

I put the print line as suggested 

```
def _resolve_addr(addr):
    if isinstance(addr, (bytes, bytearray)):
        return addr

    if not addr[0]:
        host = "127.0.0.1" if len(addr) == 2 else "::1"
    else:
        host = addr[0]
    print(repr(host), repr(addr))
    return _socket.getaddrinfo(host, addr[1])
```

And then I run ftpexample again but the same error coming out 

```
Testing
'ftp.dlptest.com' ('ftp.dlptest.com', 21)
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "ftplib.py", line 162, in __init__
  File "ftplib.py", line 219, in connect
  File "ftplib.py", line 182, in _create_connection
  File "ftplib.py", line 71, in _resolve_addr
OSError: -6
```

**Comment by SpotlightKid** [comment]
> File "ftplib.py", line 182, in _create_connection

Why does it say line 182 here? The call to `_resolve_addr` should be on line 180. Did you add any other lines?

Can you also try the following in an interactive micropython session on the Pico W with network enabled?

```py
import socket
addr = socket.getaddrinfo('ftp.dlptest.com', 21)
print(addr, repr(addr))
```

**Comment by Ricmelis80** [comment]
Hy again,

I didn't add anything in line 180, here the corresponding code from line 180 to 197 :

```
    def _create_connection(self, addr, timeout=None, source_address=None):
        sock = socket()
        addrinfos = _resolve_addr(addr)
        for af, _, _, _, addr in addrinfos:
            try:
                sock.connect(addr)
            except Exception as exc:
                print(exc)
            else:
                if timeout and timeout is not _GLOBAL_DEFAULT_TIMEOUT:
                    sock.settimeout(timeout)
                try:
                    sock.family = af
                except:
                    pass
                return sock
        else:
            raise Error("Could not connect to %r" % (addr,))"
```

Also, I tried the coding you suggested and here the response : 

```
MPY: soft reboot
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
OSError: -2"
```

**Comment by SpotlightKid** [comment]
> here the corresponding code from line 180 to 197 :

That makes no sense to me:

https://github.com/SpotlightKid/micropython-ftplib/blob/master/esp/ftplib.py#L178

Anyway, it seems that the `socket.getaddrinfo` function does not work as documented on the Pico W:

https://docs.micropython.org/en/latest/library/socket.html#socket-address-format-s

I don't know how to fix this, since I don't have a Pico W to test.

**Comment by Ricmelis80** [comment]
I see ... thanks anyway for your kindly assistence !

**Comment by Ricmelis80** [comment]
Hy again!

I finally understood where the problem lies , i.e. in the use of https:// before IP ( sorry for this, I'm not a network expert...) . The FTP request now runs properly and send regularly files in my remote server.  

Many thanks again! ATB!
