### ISSUE TITLE
unable to connect to ftp server

### ISSUE THREAD

**Issue by mouaadh11** [SpotlightKid/micropython-ftplib#17]
```py
# FTP server details
ftp_server = '44.241.66.173'
ftp_port = 21
ftp_user = 'dlpuser'
ftp_password = 'XXXXXX'

try:
    ftp.connect(ftp_server, ftp_port, timeout=30)
    ftp.set_pasv(True)  # Enable passive mode
    ftp.login(ftp_user, ftp_password)
    print("Connected to FTP server")
except ftplib.error_perm as e_perm:
    print(f"FTP Permission Error: {e_perm}")
except ftplib.error_temp as e_temp:
    print(f"FTP Temporary Error: {e_temp}")
except Exception as e:
    print(f"An error occurred: {e}")
finally:
    ftp.close()
```
```sh
Started webrepl in normal mode
An error occurred: Could not connect to ('44.241.66.173', 21)
```
I got this error while trying to establish an ftp connection between esp32 and the server

**Comment by SpotlightKid** [comment]
Did you use the version of `ftplib.py` from the `esp` directory?

It would be easier to see what's going on, if let your code print the whole exception with traceback, not just the error message.

**Comment by SpotlightKid** [comment]
BTW, I can connect to the server just fine with the unix port of micropython.

I strongly suggest you change your password after having posted it here.

**Comment by mouaadh11** [comment]
> Did you use the version of `ftplib.py` from the `esp` directory?
> 
> It would be easier to see what's going on, if let your code print the whole exception with traceback, not just the error message.

I just downloaded it as a zip and then used Thonny to upload it to the esp

**Comment by SpotlightKid** [comment]
You need to make sure that you use / upload the files in the `esp` directory, **not** the ones in the repository root folder, with the esp2866 / esp32 boards.

**Comment by mouaadh11** [comment]
> ```python
> ftp.connect(ftp_server, ftp_port, timeout=30)
> ```

can you give me the code so I can try it, I will be so thankful
