### ISSUE TITLE
Error when trying to download a file from a server AttributeError: 'SSLSocket' object has no attribute 'recv'

### ISSUE THREAD

**Issue by JuanEnHD** [SpotlightKid/micropython-ftplib#20]
Hello! I'm using the libraries inside the folder `esp`.
I want to download a file from a server with the following code:
```python
fileToWrite = open("comoEstan.txt", "wb")
def handleDownload(block):
    fileToWrite.write(block)

result = ftp.retrbinary('RETR comoEstan.txt', handleDownload)
print('ftp download comoEstan.txt return code=', result)
```
But I'm getting the following error:

Traceback (most recent call last):
  File "<stdin>", line 53, in <module>
  File "ftplib.py", line 553, in retrbinary
  File "ftplib.py", line 89, in __getattr__
AttributeError: 'SSLSocket' object has no attribute 'recv'

**Comment by SpotlightKid** [comment]
Confirmed.

Unfortunately, the SSL socket interface on the esp2866 has changed since I last tested this code. I have added some additional code to the socket compatibility wrapper in `esp/fttlib.py` in PR #22 to fix this.
